# Generated by Django 3.2.6 on 2021-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(max_length=150, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
